# Makefile for Guix Configurations

PROFILE_DIR = $(CURDIR)/env
# Use the guix from the project-local profile generated by 'guix pull'
GUIX_PULLED_CMD ?= $(PROFILE_DIR)/profile/bin/guix

# Path to our config directory (relative to Makefile)
CONFIG_DIR := $(CURDIR)/config

# Set the Guile load path so Guix can find our custom modules.
# This is more robust than using the -L flag with sudo.
GUILE_LOAD_PATH = $(CONFIG_DIR):$(CONFIG_DIR)/home-services:$(CONFIG_DIR)/util:$(CONFIG_DIR)/packages

# Use 'guix time-machine' for reproducible builds based on the lock file.
GUIX_TM = GUILE_LOAD_PATH=$(GUILE_LOAD_PATH) guix time-machine -C channels/channels-lock.scm --

# Default system and user for initial setup (can be overridden)
DEFAULT_SYSTEM ?= ser8
DEFAULT_USER ?= orka

.PHONY: all init install-system reconfigure-system reconfigure-home install-user-packages channel-update guix-pull clean

all: reconfigure-system reconfigure-home

init: guix-pull channel-update
	@echo "Initialization complete. Run 'make install-system' for a fresh install, or 'make all' to reconfigure an existing system."

install-system: guix-pull channel-update
	@echo "Installing Guix System to /mnt for $(DEFAULT_SYSTEM)..."
	sudo -E $(GUIX_TM) system init $(CONFIG_DIR)/systems/$(DEFAULT_SYSTEM)/configuration.scm /mnt

reconfigure-system:
	@echo "Reconfiguring Guix System for $(DEFAULT_SYSTEM)..."
	sudo -E $(GUIX_TM) system reconfigure $(CONFIG_DIR)/systems/$(DEFAULT_SYSTEM)/configuration.scm

reconfigure-home:
	@echo "Reconfiguring Guix Home for $(DEFAULT_USER)..."
	$(GUIX_TM) home reconfigure $(CONFIG_DIR)/users/$(DEFAULT_USER)/home.scm
	$(MAKE) install-user-packages

install-user-packages:
	@echo "Installing extra packages for user $(DEFAULT_USER)..."
	$(GUIX_TM) package -p $(HOME)/.guix-profiles/$(DEFAULT_USER)-extra -f $(CONFIG_DIR)/users/$(DEFAULT_USER)/manifest.scm

# 'channel-update' MUST use the guix from the pulled profile to see all channels.
channel-update:
	@echo "Updating channels/channels-lock.scm with current pinned channels..."
	$(GUIX_PULLED_CMD) describe --format=channels > channels/channels-lock.scm
	@echo "channels/channels-lock.scm updated."

# 'guix-pull' uses the system's 'guix' to create a project-local profile.
guix-pull:
	@echo "Running guix pull to create project-local environment..."
	mkdir -p $(PROFILE_DIR)
	guix pull --channels=channels/channels.scm --profile=$(PROFILE_DIR)/profile
	@echo "guix pull complete. Local profile is at $(PROFILE_DIR)/profile"

clean:
	@echo "Cleaning up generated files..."
	rm -f channels/channels-lock.scm
	rm -rf $(PROFILE_DIR)
	@echo "Clean complete."

# Helper for loading modules (for `guix lint`, `guix edit`, etc.)
# Usage: make -C config/modules GUILD_PATH_DIR=$(PWD)
# export GUILD_PATH=$$GUILD_PATH:$(abspath config/modules)
# Example: guix lint --load-path=$(CONFIG_DIR)/modules $(CONFIG_DIR)/users/$(DEFAULT_USER)/home.scm
# guix lint -L $(CONFIG_DIR)/modules $(CONFIG_DIR)/users/$(DEFAULT_USER)/home.scm
