# Makefile for Guix Configurations

PROFILE_DIR = $(CURDIR)/env

# Dynamically determine Guile version, fallback to 3.0 if guile executable not found.
# This assumes guile is available in the project-local profile after 'guix pull'.
GUILE_BIN := $(PROFILE_DIR)/profile/bin/guile
GUILE_VERSION := $(shell $(GUILE_BIN) -c '(display (effective-version)) (newline)' 2>/dev/null || echo "3.0")

#export GUILE_LOAD_PATH := $(CURDIR):$(PROFILE_DIR)/profile/share/guile/site/$(GUILE_VERSION)
# Use the guix from the project-local profile generated by 'guix pull'
GUIX_PULLED_CMD ?= $(PROFILE_DIR)/profile/bin/guix

# Path to our config directory (relative to Makefile)
CONFIG_DIR := $(CURDIR)/raynet-guix

# Base guix time-machine command with common load paths
GUIX_TM_BASE = GUILE_LOAD_PATH="$(CURDIR):$(PROFILE_DIR)/profile/share/guile/site/$(GUILE_VERSION)" guix time-machine --debug=4 -L $(CURDIR)

# Use 'guix time-machine' for reproducible builds based on the lock file.
# Pass custom module load paths directly to time-machine.
GUIX_TM = $(GUIX_TM_BASE) -C channels/channels-lock.scm --

# Default system and user for initial setup (can be overridden)
DEFAULT_SYSTEM ?= ser8
DEFAULT_USER ?= orka

# --- General Configuration Variables (from provided config, generalized) ---
PULL_EXTRA_OPTIONS=
# --allow-downgrades

ROOT_MOUNT_POINT=/mnt

VERSION=latest

# Alternative channel file for GUIX_ALT_TM (defaults to existing lock file)
GUIX_ALT_CHANNELS_FILE ?= channels/channels-lock.scm

# An alternative 'guix time-machine' setup, using existing load paths but allowing
# for an alternate channel file. This provides flexibility for different build contexts.
GUIX_ALT_TM = $(GUIX_TM_BASE) -C $(GUIX_ALT_CHANNELS_FILE) --

# System configuration file for live image builds
LIVE_SYSTEM_CONFIG ?= $(CONFIG_DIR)/systems/$(DEFAULT_SYSTEM)/configuration.scm
# --- End General Configuration Variables ---

.PHONY: all init install-system reconfigure-system reconfigure-home install-user-packages channel-update guix-pull clean cow-store target build-live-image target/live-image.iso target/release release-live-image

all: reconfigure-system reconfigure-home

init: guix-pull channel-update
	@echo "Initialization complete. Run 'make install-system' for a fresh install, or 'make all' to reconfigure an existing system."

install-system: guix-pull channel-update
	@echo "Installing Guix System to /mnt for $(DEFAULT_SYSTEM)..."
	@echo "DEBUG: GUILE_LOAD_PATH = ${GUILE_LOAD_PATH}"
	@echo "DEBUG: CURDIR = $(CURDIR)"
	@echo "DEBUG: CONFIG_DIR = $(CONFIG_DIR)"
	sudo -E $(GUIX_TM) system init $(CONFIG_DIR)/systems/$(DEFAULT_SYSTEM)/configuration.scm /mnt

reconfigure-system:
	@echo "Reconfiguring Guix System for $(DEFAULT_SYSTEM)..."
	sudo -E $(GUIX_TM) system reconfigure $(CONFIG_DIR)/systems/$(DEFAULT_SYSTEM)/configuration.scm

reconfigure-home:
	@echo "Reconfiguring Guix Home for $(DEFAULT_USER)..."
	$(GUIX_TM) home reconfigure $(CONFIG_DIR)/users/$(DEFAULT_USER)/home.scm
	$(MAKE) install-user-packages

install-user-packages:
	@echo "Installing extra packages for user $(DEFAULT_USER)..."
	$(GUIX_TM) package -p $(HOME)/.guix-profiles/$(DEFAULT_USER)-extra -f $(CONFIG_DIR)/users/$(DEFAULT_USER)/manifest.scm

# 'channel-update' MUST use the guix from the pulled profile to see all channels.
channel-update:
	@echo "Updating channels/channels-lock.scm with current pinned channels..."
	$(GUIX_PULLED_CMD) describe --format=channels > channels/channels-lock.scm
	@echo "channels/channels-lock.scm updated."

# 'guix-pull' uses the system's 'guix' to create a project-local profile.
guix-pull:
	@echo "Running guix pull to create project-local environment..."
	mkdir -p $(PROFILE_DIR)
	guix pull --channels=channels/channels.scm --profile=$(PROFILE_DIR)/profile
	@echo "guix pull complete. Local profile is at $(PROFILE_DIR)/profile"

clean:
	@echo "Cleaning up generated files..."
	rm -f channels/channels-lock.scm
	rm -rf $(PROFILE_DIR)
	@echo "Clean complete."

# Helper for loading modules (for `guix lint`, `guix edit`, etc.)
# Usage: make -C config/modules GUILD_PATH_DIR=$(PWD)
# export GUILD_PATH=$$GUILD_PATH:$(abspath config/modules)
# Example: guix lint --load-path=$(CONFIG_DIR)/modules $(CONFIG_DIR)/users/$(DEFAULT_USER)/home.scm
# guix lint -L $(CONFIG_DIR)/modules $(CONFIG_DIR)/users/$(DEFAULT_USER)/home.scm


# --- Generalized Targets (from provided config, adapted) ---

# Target to start the cow-store service
cow-store:
	sudo herd start cow-store ${ROOT_MOUNT_POINT}

# Utility target to create a 'target' directory
target:
	mkdir -p target

# Live image build
build-live-image:
	ALT_BUILD_TARGET=live-system $(GUIX_ALT_TM) system image --image-type=iso9660 \
	${LIVE_SYSTEM_CONFIG} -r target/live-image-tmp.iso

target/live-image.iso: build-live-image target
	mv -f target/live-image-tmp.iso target/live-image.iso

target/release:
	mkdir -p target/release

# Release packaging for live image
release-live-image: target/live-image.iso target/release
	cp -df $< target/release/live-image-${VERSION}-x86_64.iso
	gpg -ab target/release/live-image-${VERSION}-x86_64.iso
